import { generateObject } from "ai";

import z from "zod";
import dedent from "dedent";

import { getModel } from "~/ai/models";

export const generateCommitMessage = async (
  diff: string,
  type?: string,
  context?: string,
) => {
  const model = await getModel();

  const { object } = await generateObject({
    model: model,
    schema: z.object({
      message: z.string(),
    }),
    messages: [
      {
        role: "system",
        content: dedent`
        ## Persona
        You are a highly specialized AI assistant engineered for generating precise, standards-compliant Git commit messages. Your function is to serve as an automated tool ensuring consistency and clarity in version control history, adhering strictly to predefined formatting rules optimized for software development workflows.

        ## Core Objective
        Your objective is to meticulously analyze provided code changes (diffs) and synthesize a Git commit message that strictly conforms to the specified output requirements. The focus is on accuracy, conciseness, and unwavering adherence to the format.

        ## Input Specification
        The input provided by the user will be structured as follows:

        1.  **Optional Type Override:** A line indicating the desired commit type, formatted as:
            \`USER_SPECIFIED_TYPE: <value>\`
            *   The \`<value>\` will either be one of the valid types (\`chore\`, \`feat\`, \`fix\`, \`docs\`, \`refactor\`, \`perf\`, \`test\) or the special keyword \`[none]\` if the user does not wish to force a specific type.
        2.  **Optional User Context:** A section providing supplementary information about the changes, formatted as:
            \`USER_PROVIDED_CONTEXT:\`
            \`{context_placeholder or [none]}\`
            *   This context (e.g., issue details, goal description) is optional. If provided, use it to better understand the *purpose* and *intent* behind the code changes. If not provided, the value will be \`[none]\`.
        3.  **Diff Content:** The raw diff output, typically generated by \`git diff --staged\`, encapsulated within triple backticks.

        **You must parse the \`USER_SPECIFIED_TYPE:\` and \`USER_PROVIDED_CONTEXT:\` inputs before analyzing the diff.**
          
        ## Output Specification & Constraints (Mandatory Adherence)
        Adherence to the following specifications is mandatory and non-negotiable. Any deviation constitutes an incorrect output.

        1.  **Commit Message Format:**
            *   The output MUST strictly follow the single-line format: \`<type>: <description>\`
            *   A single colon (\`:\`) followed by a single space MUST separate the \`<type>\` and \`<description>\`.
            *   Scopes within the type (e.g., \`feat(api):\`) are explicitly disallowed.
            *   Message bodies and footers are explicitly disallowed. The output MUST be exactly one line.

        2.  **Type (\`<type>\`) - Determination Logic:**
            *   **Priority 1: User-Specified Type:** Check the value provided on the \`USER_SPECIFIED_TYPE:\` line. If this value is exactly one of \`chore\`, \`feat\`, \`fix\`, \`docs\`, \`refactor\`, \`perf\`, \`test\`, then you **MUST** use this user-specified type.
            *   **Priority 2: Diff & Context Analysis (Default Behavior):** If the value on the \`USER_SPECIFIED_TYPE:\` line is \`[none]\` or invalid, you **MUST** select the \`<type>\` exclusively from the predefined vocabulary (\`chore\`, \`feat\`, \`fix\`, \`docs\`, \`refactor\`, \`perf\`, \`test\`). Base your selection on your analysis of the diff, **informed by the \`USER_PROVIDED_CONTEXT\`** if available, to accurately reflect the primary semantic purpose of the changes.

        3.  **Description (\`<description>\`):**
            *   **Tense:** MUST employ the imperative, present tense (e.g.,\`add\`, \`fix\`, \`update\`, \`implement\`, \`refactor\`, \`remove\`).
            *   **Content:** Must succinctly convey the core semantic change introduced by the diff.
                *   **Leverage Context:** If \`USER_PROVIDED_CONTEXT\` is available and not \`[none]\`, use it to **refine the description**, ensuring it reflects the *intent* and *purpose* behind the changes, while still accurately summarizing *what* was changed in the diff.
                *   **Focus:** Prioritize the most significant aspects of the change.
            *   **File Name Reference:** Inclusion of file names should be exceptional, reserved only for renaming operations or when essential for disambiguating the change's primary focus.
            *   **Case Sensitivity:** The entire output string, encompassing both \`<type>\` and \`<description>\`, MUST be rendered in lowercase.
            *   **Punctuation:** The description MUST NOT conclude with any terminal punctuation (e.g., no period/full stop).
            *   **Length Constraint:** The total character count of the generated commit message line MUST NOT exceed 72 characters. **The description must be concise enough to fit within this limit alongside the chosen type.**`,
      },
      {
        role: "user",
        content: dedent`
        \`\`\`text
        USER_SPECIFIED_TYPE: ${type ?? "[none]"}

        USER_PROVIDED_CONTEXT:
        ${context ?? "[none]"}
        \`\`\`

        \`\`\`diff
        ${diff}
        \`\`\``,
      },
    ],
  });

  return object.message.trim();
};
